[[redirects]]
  from   = "/api/*"
  to     = "http://34.110.244.134/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # point your React app at the Netlify proxy
  REACT_APP_API_BASE_URL = "/api"
  REACT_APP_API_ENDPOINT_FEATURED_ITEMS = "/featuredItems"
  REACT_APP_API_ENDPOINT_SEARCH          = "/search"
  REACT_APP_API_ENDPOINT_NUM_IN_STORE    = "/numInStore"
  REACT_APP_API_ENDPOINT_FIGURES         = "/figures"
